---
# .github/workflows/build-conda.yml
name: Build and Upload Conda Package
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup rattler-build
        uses: prefix-dev/rattler-build-action@v0.2.36
        with:
          setup-only: true
      - name: Get latest commit SHA from main
        run: |
          echo "Fetching latest commit on main branch..."
          COMMIT_SHA=$(git ls-remote origin refs/heads/main | cut -f1)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
      - name: Update recipe.yaml with latest rev
        run: |
          echo "Updating recipe.yaml with commit: $COMMIT_SHA"

          # 1) Update the Jinja-set 'rev'
          sed -i "s|^{% set rev = \".*\" %}|{% set rev = \"$COMMIT_SHA\" %}|" ./recipe/recipe.yaml
      - name: Build and upload
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
        run: |
          rattler-build build --recipe recipe/recipe.yaml
          rattler-build upload anaconda --owner khanlab output/**/*.conda --force